"""
NetTap Setup Configuration API

Handles the POST /api/setup/configure endpoint that writes the capture mode
configuration and .env settings when the setup wizard completes.

Writes:
  - /opt/nettap/data/capture-mode.conf  (capture mode + interfaces)
  - /opt/nettap/data/.env               (appends/updates relevant env vars)
"""

import logging
import os
from pathlib import Path

from aiohttp import web

logger = logging.getLogger("nettap.api.setup")

# Default paths — overridable via env vars for testing
DATA_DIR = os.environ.get("NETTAP_DATA_DIR", "/opt/nettap/data")
CAPTURE_MODE_CONF = os.path.join(DATA_DIR, "capture-mode.conf")
ENV_FILE = os.environ.get("NETTAP_ENV_FILE", os.path.join(DATA_DIR, ".env"))


def _write_capture_mode_conf(config: dict) -> str:
    """Write capture-mode.conf with the selected mode and interfaces.

    Returns the path written to.
    """
    lines = [
        "# NetTap capture mode configuration",
        "# Generated by setup wizard",
        f"CAPTURE_MODE={config['capture_mode']}",
    ]

    if config["capture_mode"] == "mirror":
        lines.append(f"CAPTURE_INTERFACE={config.get('capture_interface', '')}")
        mgmt = config.get("management_interface", "")
        if mgmt:
            lines.append(f"MANAGEMENT_INTERFACE={mgmt}")
    else:
        lines.append(f"WAN_INTERFACE={config.get('wan_interface', '')}")
        lines.append(f"LAN_INTERFACE={config.get('lan_interface', '')}")

    os.makedirs(os.path.dirname(CAPTURE_MODE_CONF), exist_ok=True)
    with open(CAPTURE_MODE_CONF, "w") as f:
        f.write("\n".join(lines) + "\n")

    return CAPTURE_MODE_CONF


def _update_env_file(config: dict) -> str:
    """Append/update capture-related env vars in the .env file.

    Returns the path written to.
    """
    env_vars = {}

    env_vars["CAPTURE_MODE"] = config["capture_mode"]

    if config["capture_mode"] == "mirror":
        env_vars["CAPTURE_INTERFACE"] = config.get("capture_interface", "")
        mgmt = config.get("management_interface", "")
        if mgmt:
            env_vars["MANAGEMENT_INTERFACE"] = mgmt
    else:
        env_vars["WAN_IFACE"] = config.get("wan_interface", "")
        env_vars["LAN_IFACE"] = config.get("lan_interface", "")

    # Storage settings
    storage = config.get("storage", {})
    if storage:
        if "hot_days" in storage:
            env_vars["HOT_RETENTION_DAYS"] = str(storage["hot_days"])
        if "warm_days" in storage:
            env_vars["WARM_RETENTION_DAYS"] = str(storage["warm_days"])
        if "cold_days" in storage:
            env_vars["COLD_RETENTION_DAYS"] = str(storage["cold_days"])
        if "disk_threshold_percent" in storage:
            env_vars["DISK_THRESHOLD_PERCENT"] = str(storage["disk_threshold_percent"])
        if "emergency_threshold_percent" in storage:
            env_vars["EMERGENCY_THRESHOLD_PERCENT"] = str(
                storage["emergency_threshold_percent"]
            )

    # Read existing .env if it exists
    existing_lines = []
    existing_keys = set()
    env_path = Path(ENV_FILE)
    if env_path.exists():
        with open(env_path, "r") as f:
            for line in f:
                stripped = line.strip()
                if stripped and not stripped.startswith("#") and "=" in stripped:
                    key = stripped.split("=", 1)[0]
                    if key in env_vars:
                        # Replace with new value
                        existing_lines.append(f"{key}={env_vars[key]}\n")
                        existing_keys.add(key)
                    else:
                        existing_lines.append(line)
                else:
                    existing_lines.append(line)

    # Append any new vars not already in the file
    for key, value in env_vars.items():
        if key not in existing_keys:
            existing_lines.append(f"{key}={value}\n")

    os.makedirs(os.path.dirname(ENV_FILE), exist_ok=True)
    with open(ENV_FILE, "w") as f:
        f.writelines(existing_lines)

    return ENV_FILE


async def handle_setup_configure(request: web.Request) -> web.Response:
    """POST /api/setup/configure — Write capture mode config and .env."""
    try:
        body = await request.json()
    except Exception:
        return web.json_response(
            {"error": "Invalid JSON body"}, status=400
        )

    capture_mode = body.get("capture_mode")
    if capture_mode not in ("mirror", "bridge"):
        return web.json_response(
            {"error": "capture_mode must be 'mirror' or 'bridge'"}, status=400
        )

    # Validate required fields based on mode
    if capture_mode == "mirror":
        if not body.get("capture_interface"):
            return web.json_response(
                {"error": "capture_interface is required for mirror mode"}, status=400
            )
    else:
        if not body.get("wan_interface") or not body.get("lan_interface"):
            return web.json_response(
                {"error": "wan_interface and lan_interface are required for bridge mode"},
                status=400,
            )

    try:
        conf_path = _write_capture_mode_conf(body)
        env_path = _update_env_file(body)

        logger.info(
            "Setup configuration saved: mode=%s, conf=%s, env=%s",
            capture_mode,
            conf_path,
            env_path,
        )

        return web.json_response(
            {
                "status": "ok",
                "capture_mode": capture_mode,
                "files_written": [conf_path, env_path],
            }
        )
    except Exception as exc:
        logger.exception("Failed to save setup configuration")
        return web.json_response(
            {"error": f"Failed to save configuration: {exc}"}, status=500
        )


def register_setup_routes(app: web.Application) -> None:
    """Register setup wizard API routes."""
    app.router.add_post("/api/setup/configure", handle_setup_configure)
