#!/bin/bash
# protect-files.sh — Block edits to sensitive/generated files
# Used as a PreToolUse hook for Edit|Write tools

FILE_PATH=$(python3 -c "import sys,json; print(json.load(sys.stdin).get('tool_input',{}).get('file_path',''))" 2>/dev/null)

if [[ -z "$FILE_PATH" ]]; then
  exit 0
fi

# Extract filename from path
FILENAME="${FILE_PATH##*/}"

case "$FILE_PATH" in
  */.git/*)
    echo "BLOCKED: Files inside .git/ must never be edited directly. Use git commands instead." >&2
    exit 2
    ;;
  */package-lock.json)
    echo "BLOCKED: package-lock.json is auto-generated by npm. Run 'npm install' instead of editing it directly." >&2
    exit 2
    ;;
  */yarn.lock)
    echo "BLOCKED: yarn.lock is auto-generated by Yarn. Run 'yarn install' instead of editing it directly." >&2
    exit 2
    ;;
esac

# Check .env files by filename (.env, .env.local, .env.production, etc.)
case "$FILENAME" in
  .env|.env.*)
    echo "BLOCKED: Editing .env files is not allowed. These contain environment-specific secrets and must be edited manually." >&2
    exit 2
    ;;
esac

exit 0
