name: Bug Report
description: Report a bug or unexpected behavior
labels: ["Bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report a bug. Please fill out the fields below so we can investigate and fix the issue.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the bug.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to reproduce the behavior.
      placeholder: |
        1. Install NetTap on...
        2. Navigate to...
        3. Click on...
        4. See error...
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What you expected to happen.
      placeholder: Describe what should have happened...
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened.
      placeholder: Describe what actually happened...
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: NetTap Version
      description: The version of NetTap you are running (check with `nettap --version` or the dashboard footer).
      placeholder: "e.g., v1.0.0"
    validations:
      required: true

  - type: textarea
    id: hardware-info
    attributes:
      label: Hardware Info
      description: Details about your hardware configuration.
      placeholder: |
        CPU: Intel N100
        RAM: 16 GB DDR5
        NICs: 2x Intel i226-V 2.5GbE
        Storage: 1 TB NVMe SSD
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs
      description: Paste any relevant log output here. This will be automatically formatted as a code block.
      render: shell
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain the problem. Drag and drop images here.
    validations:
      required: false
