name: Feature Request
description: Suggest a new feature or enhancement
labels: ["Feature"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a feature! Please describe the problem you are trying to solve and your proposed solution.

  - type: textarea
    id: motivation
    attributes:
      label: Motivation / Problem
      description: Describe the problem or use case that motivates this feature request. Why is this needed?
      placeholder: |
        I'm always frustrated when...
        Currently there is no way to...
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: Describe your proposed solution or feature in detail.
      placeholder: |
        I would like NetTap to...
        The feature should work by...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you have considered.
      placeholder: |
        I considered using...
        Another approach could be...
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or screenshots about the feature request here.
    validations:
      required: false
