import { json } from '@sveltejs/kit';
import type { RequestHandler } from './$types.js';
import { daemonJSON } from '$lib/server/daemon.js';

export interface BridgeConfigRequest {
	wan_interface: string;
	lan_interface: string;
}

export interface BridgeConfigResponse {
	config_preview: string;
	wan: string;
	lan: string;
	bridge_name: string;
	ready: boolean;
	warnings: string[];
	source: 'daemon' | 'mock';
}

export const POST: RequestHandler = async ({ request }) => {
	let body: BridgeConfigRequest;

	try {
		body = await request.json();
	} catch {
		return json({ error: 'Invalid JSON body' }, { status: 400 });
	}

	const { wan_interface, lan_interface } = body;

	if (!wan_interface || !lan_interface) {
		return json({ error: 'Both wan_interface and lan_interface are required' }, { status: 400 });
	}

	if (wan_interface === lan_interface) {
		return json({ error: 'WAN and LAN interfaces must be different' }, { status: 400 });
	}

	// Try the daemon first
	const { data, error } = await daemonJSON<BridgeConfigResponse>('/api/setup/bridge', {
		method: 'POST',
		body: JSON.stringify({ wan_interface, lan_interface }),
	});

	if (data && !error) {
		return json(data);
	}

	// Daemon unavailable — return mock bridge config preview
	const warnings: string[] = [];

	const response: BridgeConfigResponse = {
		config_preview: [
			`# NetTap Bridge Configuration`,
			`# Generated by setup wizard`,
			``,
			`BRIDGE_NAME=br0`,
			`WAN_INTERFACE=${wan_interface}`,
			`LAN_INTERFACE=${lan_interface}`,
			``,
			`# Bridge will forward all traffic transparently`,
			`# No IP address assigned to bridge (Layer 2 only)`,
			`# Promiscuous mode enabled for packet capture`,
		].join('\n'),
		wan: wan_interface,
		lan: lan_interface,
		bridge_name: 'br0',
		ready: true,
		warnings,
		source: 'mock',
	};

	return json(response);
};
