FROM python:3.12-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
    smartmontools \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /opt/nettap/daemon
COPY daemon/ .

CMD ["python3", "main.py"]
