"""
NetTap MACCorrelator — Detect randomized MAC addresses and correlate devices.

Detects locally-administered (randomized) MACs, builds behavioral fingerprints
from DNS patterns, JA3 TLS fingerprints, destination IPs, timing, and traffic
volume. Suggests device merges with confidence scores.

A locally-administered MAC has bit 1 of the first octet set:
    int(mac.split(':')[0], 16) & 0x02 != 0
"""

import json
import logging
import os
import uuid
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from opensearchpy import OpenSearchException

logger = logging.getLogger("nettap.services.mac_correlator")

NETWORK_INDEX = os.environ.get("OPENSEARCH_NETWORK_INDEX", "arkime_sessions3-*")

# Merge history persistence
_DEFAULT_MERGE_FILE = os.environ.get(
    "MAC_MERGE_FILE", "/opt/nettap/data/mac_merges.json"
)

# Confidence thresholds
_HIGH_CONFIDENCE = 0.80
_MEDIUM_CONFIDENCE = 0.50


def is_randomized_mac(mac: str) -> bool:
    """Check if a MAC address is locally-administered (randomized).

    The locally-administered bit is bit 1 of the first octet. If set,
    the MAC was generated by software (iOS/Android/Windows privacy feature),
    not assigned by a manufacturer.
    """
    try:
        first_octet = int(mac.split(":")[0], 16)
        return bool(first_octet & 0x02)
    except (ValueError, IndexError):
        return False


class MACCorrelator:
    """Detect randomized MACs and correlate them to real devices."""

    def __init__(
        self,
        client: Any,
        merge_file: str | None = None,
    ) -> None:
        self._client = client
        self._merge_file = Path(merge_file or _DEFAULT_MERGE_FILE)
        self._merge_history: list[dict[str, Any]] = []
        self._load_merge_history()

    # ------------------------------------------------------------------
    # Merge history persistence
    # ------------------------------------------------------------------

    def _load_merge_history(self) -> None:
        """Load merge history from JSON file."""
        if self._merge_file.exists():
            try:
                data = json.loads(self._merge_file.read_text())
                self._merge_history = data if isinstance(data, list) else []
                logger.info("Loaded %d MAC merge records", len(self._merge_history))
            except (json.JSONDecodeError, OSError) as exc:
                logger.warning("Failed to load MAC merge history: %s", exc)
                self._merge_history = []
        else:
            self._merge_history = []

    def _save_merge_history(self) -> None:
        """Persist merge history to JSON file."""
        try:
            self._merge_file.parent.mkdir(parents=True, exist_ok=True)
            self._merge_file.write_text(
                json.dumps(self._merge_history, indent=2, default=str)
            )
        except OSError as exc:
            logger.error("Failed to save MAC merge history: %s", exc)

    # ------------------------------------------------------------------
    # Randomized MAC detection
    # ------------------------------------------------------------------

    def detect_randomized_macs(
        self, from_ts: str, to_ts: str
    ) -> list[dict[str, Any]]:
        """Find MACs with the locally-administered bit set in traffic data.

        Returns a list of dicts with mac, connection_count, first_seen, last_seen,
        total_bytes, and top_destinations.
        """
        query = {
            "size": 0,
            "query": {
                "bool": {
                    "filter": [
                        {
                            "range": {
                                "@timestamp": {
                                    "gte": from_ts,
                                    "lte": to_ts,
                                    "format": "strict_date_optional_time",
                                }
                            }
                        }
                    ]
                }
            },
            "aggs": {
                "macs": {
                    "terms": {
                        "field": "source.mac.keyword",
                        "size": 500,
                    },
                    "aggs": {
                        "first_seen": {"min": {"field": "@timestamp"}},
                        "last_seen": {"max": {"field": "@timestamp"}},
                        "total_bytes": {
                            "sum": {
                                "script": {
                                    "source": (
                                        "(doc['client.bytes'].size() > 0 ? doc['client.bytes'].value : 0) "
                                        "+ (doc['server.bytes'].size() > 0 ? doc['server.bytes'].value : 0)"
                                    ),
                                    "lang": "painless",
                                }
                            }
                        },
                        "top_dests": {
                            "terms": {
                                "field": "destination.ip.keyword",
                                "size": 5,
                            }
                        },
                    },
                }
            },
        }

        try:
            result = self._client.search(index=NETWORK_INDEX, body=query)
        except OpenSearchException as exc:
            logger.error("OpenSearch error detecting randomized MACs: %s", exc)
            return []

        buckets = result.get("aggregations", {}).get("macs", {}).get("buckets", [])
        randomized = []

        for bucket in buckets:
            mac = bucket["key"]
            if is_randomized_mac(mac):
                top_dests = [
                    d["key"]
                    for d in bucket.get("top_dests", {}).get("buckets", [])
                ]
                randomized.append({
                    "mac": mac,
                    "connection_count": bucket["doc_count"],
                    "first_seen": bucket.get("first_seen", {}).get("value_as_string"),
                    "last_seen": bucket.get("last_seen", {}).get("value_as_string"),
                    "total_bytes": bucket.get("total_bytes", {}).get("value", 0),
                    "top_destinations": top_dests,
                })

        logger.info(
            "Found %d randomized MACs out of %d total",
            len(randomized),
            len(buckets),
        )
        return randomized

    # ------------------------------------------------------------------
    # Behavioral fingerprinting
    # ------------------------------------------------------------------

    def get_behavioral_fingerprint(
        self, mac: str, from_ts: str, to_ts: str
    ) -> dict[str, Any]:
        """Build a behavioral fingerprint for a MAC address.

        The fingerprint includes:
        - dns_patterns: top queried domains
        - tls_fingerprints: JA3 hashes seen
        - destination_ips: top destination IPs
        - timing_pattern: hourly activity distribution
        - traffic_profile: bytes sent/received, avg packet size
        """
        time_filter = {
            "range": {
                "@timestamp": {
                    "gte": from_ts,
                    "lte": to_ts,
                    "format": "strict_date_optional_time",
                }
            }
        }
        mac_filter = {"term": {"source.mac.keyword": mac}}

        fingerprint: dict[str, Any] = {
            "mac": mac,
            "is_randomized": is_randomized_mac(mac),
            "dns_patterns": [],
            "tls_fingerprints": [],
            "destination_ips": [],
            "timing_pattern": [],
            "traffic_profile": {},
        }

        # Query 1: DNS patterns + destinations + traffic profile
        main_query = {
            "size": 0,
            "query": {"bool": {"filter": [time_filter, mac_filter]}},
            "aggs": {
                "dns_domains": {
                    "terms": {
                        "field": "dns.question.name.keyword",
                        "size": 20,
                    }
                },
                "dest_ips": {
                    "terms": {
                        "field": "destination.ip.keyword",
                        "size": 20,
                    }
                },
                "ja3_hashes": {
                    "terms": {
                        "field": "tls.ja3.keyword",
                        "size": 10,
                    }
                },
                "hourly_activity": {
                    "date_histogram": {
                        "field": "@timestamp",
                        "calendar_interval": "hour",
                    }
                },
                "total_orig_bytes": {
                    "sum": {"field": "client.bytes", "missing": 0}
                },
                "total_resp_bytes": {
                    "sum": {"field": "server.bytes", "missing": 0}
                },
                "total_orig_pkts": {
                    "sum": {"field": "source.packets", "missing": 0}
                },
                "total_resp_pkts": {
                    "sum": {"field": "destination.packets", "missing": 0}
                },
            },
        }

        try:
            result = self._client.search(index=NETWORK_INDEX, body=main_query)
            aggs = result.get("aggregations", {})

            fingerprint["dns_patterns"] = [
                {"domain": b["key"], "count": b["doc_count"]}
                for b in aggs.get("dns_domains", {}).get("buckets", [])
            ]
            fingerprint["tls_fingerprints"] = [
                {"ja3": b["key"], "count": b["doc_count"]}
                for b in aggs.get("ja3_hashes", {}).get("buckets", [])
            ]
            fingerprint["destination_ips"] = [
                {"ip": b["key"], "count": b["doc_count"]}
                for b in aggs.get("dest_ips", {}).get("buckets", [])
            ]
            fingerprint["timing_pattern"] = [
                {
                    "hour": b.get("key_as_string", b.get("key")),
                    "connections": b["doc_count"],
                }
                for b in aggs.get("hourly_activity", {}).get("buckets", [])
            ]

            orig_bytes = aggs.get("total_orig_bytes", {}).get("value", 0) or 0
            resp_bytes = aggs.get("total_resp_bytes", {}).get("value", 0) or 0
            orig_pkts = aggs.get("total_orig_pkts", {}).get("value", 0) or 0
            resp_pkts = aggs.get("total_resp_pkts", {}).get("value", 0) or 0
            total_pkts = orig_pkts + resp_pkts

            fingerprint["traffic_profile"] = {
                "orig_bytes": orig_bytes,
                "resp_bytes": resp_bytes,
                "total_bytes": orig_bytes + resp_bytes,
                "orig_packets": orig_pkts,
                "resp_packets": resp_pkts,
                "avg_packet_size": (
                    (orig_bytes + resp_bytes) / total_pkts if total_pkts > 0 else 0
                ),
            }

        except OpenSearchException as exc:
            logger.error(
                "OpenSearch error building fingerprint for %s: %s", mac, exc
            )

        return fingerprint

    # ------------------------------------------------------------------
    # Merge suggestions
    # ------------------------------------------------------------------

    def _compute_similarity(
        self, fp_a: dict[str, Any], fp_b: dict[str, Any]
    ) -> float:
        """Compute behavioral similarity between two fingerprints (0.0-1.0).

        Weights:
        - DNS patterns overlap: 0.35
        - JA3 fingerprint overlap: 0.25
        - Destination IP overlap: 0.25
        - Traffic volume similarity: 0.15
        """
        scores: list[tuple[float, float]] = []

        # DNS overlap
        dns_a = {d["domain"] for d in fp_a.get("dns_patterns", [])}
        dns_b = {d["domain"] for d in fp_b.get("dns_patterns", [])}
        if dns_a or dns_b:
            overlap = len(dns_a & dns_b)
            total = len(dns_a | dns_b)
            scores.append((overlap / total if total > 0 else 0, 0.35))
        else:
            scores.append((0, 0.35))

        # JA3 overlap
        ja3_a = {j["ja3"] for j in fp_a.get("tls_fingerprints", [])}
        ja3_b = {j["ja3"] for j in fp_b.get("tls_fingerprints", [])}
        if ja3_a or ja3_b:
            overlap = len(ja3_a & ja3_b)
            total = len(ja3_a | ja3_b)
            scores.append((overlap / total if total > 0 else 0, 0.25))
        else:
            scores.append((0, 0.25))

        # Destination IP overlap
        dest_a = {d["ip"] for d in fp_a.get("destination_ips", [])}
        dest_b = {d["ip"] for d in fp_b.get("destination_ips", [])}
        if dest_a or dest_b:
            overlap = len(dest_a & dest_b)
            total = len(dest_a | dest_b)
            scores.append((overlap / total if total > 0 else 0, 0.25))
        else:
            scores.append((0, 0.25))

        # Traffic volume similarity (ratio of smaller to larger)
        vol_a = fp_a.get("traffic_profile", {}).get("total_bytes", 0)
        vol_b = fp_b.get("traffic_profile", {}).get("total_bytes", 0)
        if vol_a > 0 and vol_b > 0:
            ratio = min(vol_a, vol_b) / max(vol_a, vol_b)
            scores.append((ratio, 0.15))
        else:
            scores.append((0, 0.15))

        # Weighted sum
        total_weight = sum(w for _, w in scores)
        if total_weight == 0:
            return 0.0
        return sum(s * w for s, w in scores) / total_weight

    def suggest_merges(
        self, from_ts: str, to_ts: str
    ) -> list[dict[str, Any]]:
        """Compare randomized MACs to known devices and suggest merges.

        Returns a list of merge candidates with confidence scores.
        """
        randomized = self.detect_randomized_macs(from_ts, to_ts)
        if not randomized:
            return []

        # Get all MACs for fingerprinting
        all_macs_query = {
            "size": 0,
            "query": {
                "bool": {
                    "filter": [
                        {
                            "range": {
                                "@timestamp": {
                                    "gte": from_ts,
                                    "lte": to_ts,
                                    "format": "strict_date_optional_time",
                                }
                            }
                        }
                    ]
                }
            },
            "aggs": {
                "macs": {
                    "terms": {"field": "source.mac.keyword", "size": 500}
                }
            },
        }

        try:
            result = self._client.search(index=NETWORK_INDEX, body=all_macs_query)
        except OpenSearchException as exc:
            logger.error("OpenSearch error finding known MACs: %s", exc)
            return []

        all_mac_buckets = (
            result.get("aggregations", {}).get("macs", {}).get("buckets", [])
        )
        randomized_set = {r["mac"] for r in randomized}
        known_macs = [
            b["key"]
            for b in all_mac_buckets
            if not is_randomized_mac(b["key"]) and b["key"] not in randomized_set
        ]

        if not known_macs:
            return []

        suggestions = []

        for rand_entry in randomized:
            rand_mac = rand_entry["mac"]
            rand_fp = self.get_behavioral_fingerprint(rand_mac, from_ts, to_ts)

            best_match: dict[str, Any] | None = None
            best_score = 0.0

            for known_mac in known_macs:
                known_fp = self.get_behavioral_fingerprint(
                    known_mac, from_ts, to_ts
                )
                score = self._compute_similarity(rand_fp, known_fp)

                if score > best_score and score >= _MEDIUM_CONFIDENCE:
                    best_score = score
                    best_match = {
                        "mac_randomized": rand_mac,
                        "mac_real": known_mac,
                        "confidence": round(score, 3),
                        "confidence_level": (
                            "high" if score >= _HIGH_CONFIDENCE else "medium"
                        ),
                        "shared_dns": list(
                            {d["domain"] for d in rand_fp.get("dns_patterns", [])}
                            & {d["domain"] for d in known_fp.get("dns_patterns", [])}
                        )[:5],
                        "shared_ja3": list(
                            {j["ja3"] for j in rand_fp.get("tls_fingerprints", [])}
                            & {j["ja3"] for j in known_fp.get("tls_fingerprints", [])}
                        )[:3],
                        "shared_destinations": list(
                            {d["ip"] for d in rand_fp.get("destination_ips", [])}
                            & {d["ip"] for d in known_fp.get("destination_ips", [])}
                        )[:5],
                    }

            if best_match:
                suggestions.append(best_match)

        # Sort by confidence descending
        suggestions.sort(key=lambda s: s["confidence"], reverse=True)

        logger.info(
            "Found %d merge suggestions from %d randomized MACs",
            len(suggestions),
            len(randomized),
        )
        return suggestions

    # ------------------------------------------------------------------
    # Merge / undo
    # ------------------------------------------------------------------

    def merge_devices(self, mac_randomized: str, mac_real: str) -> dict[str, Any]:
        """Record a device merge (randomized MAC -> real MAC).

        This creates a merge record that can be used by the device registry
        to consolidate traffic and device information.
        """
        merge_record = {
            "id": str(uuid.uuid4()),
            "mac_randomized": mac_randomized.lower(),
            "mac_real": mac_real.lower(),
            "merged_at": datetime.now(timezone.utc).isoformat(),
            "status": "active",
        }

        self._merge_history.append(merge_record)
        self._save_merge_history()

        logger.info(
            "Merged randomized MAC %s -> real MAC %s",
            mac_randomized,
            mac_real,
        )
        return merge_record

    def undo_merge(self, merge_id: str) -> bool:
        """Undo a previous merge by marking it inactive."""
        for record in self._merge_history:
            if record.get("id") == merge_id:
                record["status"] = "undone"
                record["undone_at"] = datetime.now(timezone.utc).isoformat()
                self._save_merge_history()
                logger.info("Undid merge %s", merge_id)
                return True
        return False

    def get_merge_history(self) -> list[dict[str, Any]]:
        """Return all merge records (active and undone)."""
        return list(self._merge_history)

    def get_active_merges(self) -> dict[str, str]:
        """Return a dict mapping randomized MAC -> real MAC for active merges."""
        return {
            r["mac_randomized"]: r["mac_real"]
            for r in self._merge_history
            if r.get("status") == "active"
        }
